# Container Image
FROM python:3.10-slim

# Environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install build deps and FFmpeg
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libffi-dev ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Install requirements
COPY requirements.txt /
RUN pip3 install -r /requirements.txt

# Copy static folder
COPY ./Onani/static /static

# Copy working dir to root of virtual drive
COPY . /onani

# Set workdir
WORKDIR /onani

# Load entrypoint
ENTRYPOINT ["./entrypoints/entrypoint.dev.sh"]