# @Author: kapsikkum
# @Date:   2022-03-01 15:19:02
# @Last Modified by:   kapsikkum
# @Last Modified time: 2022-03-04 18:46:47
version: '3.8'

services:
  flask:
    build:
      context: .
    ports:
    - 5001:5000
    environment:
      FLASK_APP: run
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
    - images:/images

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - 5000:80
    depends_on:
      - flask
    volumes:
    - images:/images

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: onani_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  database:
  images:
