# @Author: kapsikkum
# @Date:   2022-03-01 15:19:02
# @Last Modified by:   kapsikkum
# @Last Modified time: 2022-04-10 15:16:03
version: '3.8'

services:
  flask:
    build:
      context: .
    ports:
    - 5000:5000
    environment:
      FLASK_APP: run
      FLASK_ENV: development
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:-dev}
      FLASK_SQLALCHEMY_ECHO: "True"
      TESTING: "True"
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      DB_PASSWORD: ${DB_PASSWORD:-onani_db} 
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    - images:/images
    - avatars:/avatars
    - migrations:/onani/migrations
    - logs:/logs
    - ./:/onani

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - 8080:80
    depends_on:
      - flask
    volumes:
    - images:/images
    - avatars:/avatars
    - logs:/logs
    - ./Onani/static:/static

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - PGUSER=onani_db
      - POSTGRES_USER=onani_db
      - POSTGRES_PASSWORD=${DB_PASSWORD:-onani_db}
      - POSTGRES_DB=onani_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # redis:
  #   image: redis:alpine

volumes:
  database:
  images:
  avatars:
  migrations:
  logs:
