# @Author: kapsikkum
# @Date:   2022-03-01 15:19:02
# @Last Modified by:   kapsikkum
# @Last Modified time: 2022-04-30 16:27:14
version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile:
        dockerfile.dev
    ports:
    - 5000:5000
    environment:
      FLASK_APP: run
      FLASK_ENV: development
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:-dev}
      FLASK_SQLALCHEMY_ECHO: "True"
      TESTING: "True"
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      DB_PASSWORD: ${DB_PASSWORD:-onani_db} 
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
    - images:/images
    - avatars:/avatars
    # - migrations:/onani/migrations
    - logs:/logs
    - ./:/onani

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - 8080:80
    depends_on:
      - flask
    volumes:
    - images:/images
    - avatars:/avatars
    - logs:/logs
    - ./Onani/static:/static

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - PGUSER=onani_db
      - POSTGRES_USER=onani_db
      - POSTGRES_PASSWORD=${DB_PASSWORD:-onani_db}
      - POSTGRES_DB=onani_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  redis:
    image: redis:7.0.0-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  celery:
    build:
      context: .
      dockerfile:
        ./celery/dockerfile.dev
    environment:
      FLASK_APP: run
      FLASK_ENV: development
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:-dev}
      FLASK_SQLALCHEMY_ECHO: "True"
      TESTING: "True"
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      DB_PASSWORD: ${DB_PASSWORD:-onani_db}
      C_FORCE_ROOT: "yes"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
    - images:/images
    - avatars:/avatars
    # - ./migrations:/onani/migrations
    - logs:/logs
    - ./:/onani

volumes:
  database:
  images:
  avatars:
  # migrations:
  logs:
