# @Author: kapsikkum
# @Date:   2022-03-01 15:19:02
# @Last Modified by:   kapsikkum
# @Last Modified time: 2022-03-01 19:34:24
version: '3.8'

services:
 web_server:
  build:
   context: .
  ports:
  - 5000:5000
  depends_on:
    mysql_db:
      condition: service_healthy
  command: ["python init_db.py"]


 mysql_db:
  image: mysql
  ports:
  - 3306:3306
  environment:
    MYSQL_DATABASE: onani_db
    MYSQL_ROOT_PASSWORD: root
  volumes:
  - database:/var/lib/mysql
  healthcheck:
    test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    timeout: 20s
    retries: 10

volumes:
  database:
