version: "3.9"

services:
  app:
    image: ghcr.io/onani-dev/onani-app:1.0.0-beta.22
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      FLASK_APP: run
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./images:/images
      - ./avatars:/avatars
      - ./migrations:/onani/migrations

  celery:
    image: ghcr.io/onani-dev/onani-celery:1.0.0-beta.22
    restart: unless-stopped
    environment:
      FLASK_APP: run
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./images:/images
      - ./avatars:/avatars
      - ./migrations:/onani/migrations

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: onani_db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: onani_db
    volumes:
      - ./database:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U onani_db -d onani_db -h 127.0.0.1 -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  database:
  images:
  avatars:
