# -*- coding: utf-8 -*-
# @Author: kapsikkum
# @Date:   2022-03-16 15:16:39
# @Last Modified by:   kapsikkum
# @Last Modified time: 2022-05-30 16:52:11
from enum import IntFlag


class UserPermissions(IntFlag):
    """User Permissions Flags"""

    # POSTS
    CREATE_POSTS = 1
    DELETE_POSTS = 2
    EDIT_POSTS = 4
    IMPORT_POSTS = 8
    MERGE_POSTS = 16

    # TAGS
    CREATE_TAGS = 32
    DELETE_TAGS = 64
    EDIT_TAGS = 128
    IMPORT_TAGS = 256
    MERGE_TAGS = 512

    # COLLECTIONS
    CREATE_COLLECTIONS = 1024
    DELETE_COLLECTIONS = 2048
    EDIT_COLLECTIONS = 4096
    MERGE_COLLECTIONS = 8192

    # FLAGGING
    CAN_FLAG = 16384
    PRIORITY_FLAG = 32768

    # COMMENTS
    CREATE_COMMENTS = 65536
    DELETE_COMMENTS = 131072
    LOCK_COMMENTS = 262144

    # NEWS
    CREATE_NEWS = 524288
    DELETE_NEWS = 1048576
    EDIT_NEWS = 2097152

    # USERS
    BAN_USERS = 4194304
    CREATE_USERS = 8388608
    DELETE_USERS = 16777216
    EDIT_USERS = 33554432

    # SITE
    BYPASS_RATELIMIT = 67108864
    VIEW_LOGS = 134217728

    # PRESETS
    READONLY = 268435456

    DEFAULT = CREATE_POSTS | CREATE_COMMENTS | CREATE_COLLECTIONS | CAN_FLAG

    TRUSTED = DEFAULT | CREATE_TAGS | IMPORT_POSTS | PRIORITY_FLAG

    MODERATION = (
        TRUSTED
        | EDIT_POSTS
        | MERGE_POSTS
        | EDIT_TAGS
        | MERGE_TAGS
        | EDIT_COLLECTIONS
        | MERGE_COLLECTIONS
        | DELETE_COMMENTS
        | LOCK_COMMENTS
    )

    ADMINISTRATION = (
        MODERATION
        | DELETE_POSTS
        | DELETE_TAGS
        | DELETE_COLLECTIONS
        | CREATE_NEWS
        | DELETE_NEWS
        | EDIT_NEWS
        | BAN_USERS
        | CREATE_USERS
        | DELETE_USERS
        | EDIT_USERS
        | BYPASS_RATELIMIT
        | VIEW_LOGS
    )
