FROM nginx:1.21-alpine

COPY ./Onani/static /static
RUN chown nginx:nginx /static/*

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d


RUN rm /etc/nginx/nginx.conf
COPY ./nginx/nginx_sys.conf /etc/nginx/nginx.conf
# RUN echo "load_module /etc/nginx/modules/ngx_http_image_filter_module.so;" >> /etc/nginx/nginx.conf