upstream onani {
    server flask:5000;
}

server {
    # Port to listen to
    listen 80;

    # ssl http2
    # Logging
    access_log /dev/stdout; # print access log to stdout
    error_log /dev/stdout info; # print info level error log to stdout
    access_log /logs/onani.access.log;
    error_log /logs/onani.error.log;

    # values of stuff
    client_max_body_size 200M;
    image_filter_buffer 50M;
    
    ## START ROOT FILES
    ## THESE FILES NEED TO BE ON ROOT FOR VARIOUS REASONS
    ## FUCK W3

    # Robots.txt
    location /robots.txt {
        access_log off;
        alias /static/robots.txt;
    }

    # Webmanifest
    location /site.webmanifest {
        access_log off;
        alias /static/site.webmanifest;
    }

    # Webmanifest
    location /manifest.json {
        access_log off;
        alias /static/manifest.json;
    }

    # Pwabuilder Serviceworker
    location /pwabuilder-sw.js {
        access_log off;
        alias /static/pwabuilder-sw.js;
    }

    ## END ROOT FILES
    ## THANK GOD IT'S OVER.

    # Image location
    location /images/ {
        access_log off;
        alias /images/;
    }

    # Avatar location
    location /avatars/ {
        access_log off;
        alias /avatars/;
    }

    # Static file location (js css etc)
    location /static/ {
        access_log off;
        alias /static/;
    }

    # thumbnail endpoint
    location ~ ^/thumbnail/(?<width>\d+)x(?<height>\d+)/(?<route>(avatars|images))/(?<name>.*)$ {
        access_log off;
        image_filter resize $width $height;
        alias /$route/$name;
    }


    # Proxy to the gunicorn wsgi server
    location / {
        proxy_pass http://onani;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }

    # location ~* \.(jpg|jpeg|webm|webp|png|gif|ico|css|js|otf|txt)$ {
    #     access_log off;
    #     expires 7d;
    # }

    # # caching shit idk forgor
    # proxy_cache images;
    # proxy_cache_lock on;
    # proxy_cache_valid 30d;
    # proxy_cache_use_stale error timeout invalid_header updating;
    # expires 30d;

}