upstream onani {
    server flask:5000;
}

server {
    # Port to listen to
    listen 80;
    listen 443;

    # ssl http2
    # Logging
    access_log /logs/onani.access.log;
    error_log /logs/onani.error.log;

    # values of stuff
    client_max_body_size 200M;
    image_filter_buffer 50M;

    # Robuts .tixt
    location /robots.txt { # doing this bc robots.txt file should be on root of the site.
        alias /static/robots.txt;
    }

    # Image location
    location /images/ {
        alias /images/;
    }

    # Avatar location
    location /avatars/ {
        alias /avatars/;
    }

    # Static file location (js css etc)
    location /static/ {
        alias /static/;
    }

    # thumbnail endpoint
    location ~ ^/thumbnail/(?<width>\d+)x(?<height>\d+)/(?<route>(avatars|images))/(?<name>.*)$ {
        image_filter resize $width $height;
        alias /$route/$name;
    }

    # Proxy to the gunicorn wsgi server
    location / {
        proxy_pass http://onani;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }

    # location ~* \.(jpg|jpeg|webm|webp|png|gif|ico|css|js|otf|txt)$ {
    #     access_log off;
    #     expires 7d;
    # }

    # # caching shit idk forgor
    # proxy_cache images;
    # proxy_cache_lock on;
    # proxy_cache_valid 30d;
    # proxy_cache_use_stale error timeout invalid_header updating;
    # expires 30d;

}